CREATE TABLE "user"(
	ID_USER INT PRIMARY KEY,
	NAME VARCHAR(50),
	USERNAME VARCHAR(50),
	PASSWORD VARCHAR(50),
	PHONE VARCHAR(50),
); 

-- tabla para proveedores para evitar cualquier error
CREATE TABLE proveedor (
    id_proveedor NUMBER PRIMARY KEY,
    nom_proveedor VARCHAR2(255),
    id_direccion NUMBER,
    rtn VARCHAR2(255),
    id_tel NUMBER,
    correo VARCHAR2(255),
    id_vendedor NUMBER,
    adj_doc BLOB
);

-- TABLA DEPARTAMENTO
CREATE TABLE DEPARTAMENTO (
    ID_DEPARTAMENTO INT NOT NULL,
    NOMBRE_DEPARTAMENTO VARCHAR(255),
	CONSTRAINT PK_DEPTO PRIMARY KEY (ID_DEPARTAMENTO),
    CONSTRAINT UN_NOMBRE_DEPTO UNIQUE (NOMBRE_DEPARTAMENTO)
);

-- TABLA MUNICIPIO
CREATE TABLE MUNICIPIO (
    ID_MUNICIPIO INT NOT NULL,
    NOMBRE_MUNICIPIO VARCHAR(255),
    ID_DEPARTAMENTO INT,
	CONSTRAINT PK_MUNI PRIMARY KEY (ID_MUNICIPIO),
    CONSTRAINT FK_DEPTO FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO)
);

-- TABLA CIUDAD
CREATE TABLE CIUDAD (
    ID_CIUDAD INT NOT NULL,
    NOMBRE_CIUDAD VARCHAR(255),
    ID_MUNICIPIO INT,
	CONSTRAINT PK_CIUDAD PRIMARY KEY (ID_CIUDAD),
    CONSTRAINT FK_MUNI FOREIGN KEY (ID_MUNICIPIO) REFERENCES MUNICIPIO(ID_MUNICIPIO)
);


-- Tabla para N�mero de Tel�fono
CREATE TABLE TELEFONO (
    ID_TEL INT,
    NUM_TEL VARCHAR(15),
	CONSTRAINT PK_TEL PRIMARY KEY (ID_TEL)
);

-- Tabla para Direcci�n Exacta
CREATE TABLE DIRECCION (
    ID_DIRECCION INT,
    DIRECCION VARCHAR(255),
	ID_CIUDAD INT,
	CONSTRAINT PK_DIRECCION PRIMARY KEY (ID_DIRECCION),
	CONSTRAINT FK_CIUDAD FOREIGN KEY (ID_CIUDAD) REFERENCES CIUDAD (ID_CIUDAD)
);


-- TABLA PERSONA
CREATE TABLE PERSONA (
    ID_PERSONA INT NOT NULL,
	P_NOMBRE VARCHAR(50),
    S_NOMBRE VARCHAR(50),
    P_APELLIDO VARCHAR(50),
    S_APELLIDO VARCHAR(50),
	FECHA_NACIMIEMTO DATE,
    NUM_DNI VARCHAR(20) UNIQUE NOT NULL,
	RTN VARCHAR (14) UNIQUE, 
	ID_TEL INT,
	ID_DIRECCION INT,
	CORREO VARCHAR (100) UNIQUE,
    CONSTRAINT PK_PERSONA_ID PRIMARY KEY (ID_PERSONA),
    CONSTRAINT FK_TELEFONO FOREIGN KEY (ID_TEL) REFERENCES TELEFONO(ID_TEL),
	CONSTRAINT FK_DIRECCION_ESPECIFICA FOREIGN KEY (ID_DIRECCION) REFERENCES DIRECCION(ID_DIRECCION)
);

-- TABLA NATURALEZA DEL CLIENTE
CREATE TABLE TIPO_CLIENTE (
	ID_TIPO INT  NOT NULL,
    TIPO_CLIE VARCHAR(255) NOT NULL CHECK (TIPO_CLIE IN ('Natural', 'Jur�dico')),
	CONSTRAINT PK_TIPO_CLIENTE PRIMARY KEY (ID_TIPO)
);

---TABLA DEL CLIENTE NATURAL
CREATE TABLE CLIENTE_NATURAL(
	ID_CLIENTE INT, 
	ID_PERSONA INT,
	ID_TIPO INT,
	CONSTRAINT PK_CLIENTE_NAT PRIMARY KEY (ID_CLIENTE),
	CONSTRAINT FK_PERSONA_NAT FOREIGN KEY (ID_PERSONA) REFERENCES PERSONA (ID_PERSONA),
	CONSTRAINT FK_TIPO_CLIE FOREIGN KEY (ID_TIPO) REFERENCES TIPO_CLIENTE (ID_TIPO)

);
--- TABLA DE LA EMPRESA
CREATE TABLE EMPRESA (
	ID_EMPRESA INT,
	ID_TIPO INT,
	NOM_EMPRESA VARCHAR(255) NOT NULL,
	ID_DIRECCION INT,
	RTN VARCHAR (14) UNIQUE, 
	ID_TEL INT,
	CORREO VARCHAR (100) UNIQUE,
	CONSTRAINT PK_EMPRESA PRIMARY KEY (ID_EMPRESA),
	CONSTRAINT FK_DIRECCION_EMP FOREIGN KEY (ID_DIRECCION) REFERENCES DIRECCION(ID_DIRECCION),
	CONSTRAINT FK_TELEFONO_EMP FOREIGN KEY (ID_TEL) REFERENCES TELEFONO(ID_TEL),
	CONSTRAINT FK_TIPO_CLIENTE FOREIGN KEY (ID_TIPO) REFERENCES TIPO_CLIENTE (ID_TIPO)
);

-- Tabla para CONTACTO DE LA EMPRESA
CREATE TABLE CONTACTO_EMPRESA (
    ID_CONTACTO_EMP INT PRIMARY KEY,
    ID_EMPRESA INT NOT NULL,
	P_NOMBRE VARCHAR(50),
    S_NOMBRE VARCHAR(50),
    P_APELLIDO VARCHAR(50),
    S_APELLIDO VARCHAR(50),
	FECHA_NACIMIEMTO DATE,
    NUM_DNI VARCHAR(20) UNIQUE NOT NULL,
	RTN VARCHAR (14) UNIQUE, 
	ID_TEL INT,
	ID_DIRECCION INT,
    RAZON_SOCIAL VARCHAR(255),
	CORREO VARCHAR (100) UNIQUE,
    CONSTRAINT FK_TELEFONO_CONTACTO FOREIGN KEY (ID_TEL) REFERENCES TELEFONO(ID_TEL),
	CONSTRAINT FK_DIRECCION_ESPECIFICA_CONTACTO FOREIGN KEY (ID_DIRECCION) REFERENCES DIRECCION(ID_DIRECCION),
    CONSTRAINT FK_CONTACTO_EMPRESA FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA(ID_EMPRESA)
);


-- TABLA CARGO
CREATE TABLE CARGO (
    ID_CARGO INT NOT NULL,
    NOMBRE_CARGO VARCHAR(255),
	CONSTRAINT PK_CARGO PRIMARY KEY (ID_CARGO)
);
---- TABLA DEL ESTADO CIVIL DEL EMPLEADO
CREATE TABLE ESTADO_CIVIL (
	ID_ESTADO_CIVIL INT,
	ESTADO VARCHAR(255),
	CONSTRAINT PK_ESTADO_CIVIL PRIMARY KEY (ID_ESTADO_CIVIL) 
);
----TABLA DE TIPO DE PARENTESCO DEL CONTACTO CON EL EMPLEADO
CREATE TABLE PARENTESCO (
	ID_PARENTESCO INT,
	TIPO VARCHAR (255),
	CONSTRAINT PK_PARENTESCO PRIMARY KEY (ID_PARENTESCO)
);
-----TABLE DE CONTACTO DE EMERGENCIA DEL EMPLEADO
CREATE TABLE CONTACTO_EMERGENGIA (
	ID_CONTACTO_EMER INT,
	NOM_CONTACTO_EMER VARCHAR(255),
	TEL_CONTACTO_EMER INT,
	ID_PARENTESCO INT,
	ID_DIRECCION_EMER INT,
	CONSTRAINT PK_CONTACTO_EMERG PRIMARY KEY (ID_CONTACTO_EMER),
	CONSTRAINT FK_TELEFONO_EMER FOREIGN KEY (TEL_CONTACTO_EMER) REFERENCES TELEFONO(ID_TEL),
	CONSTRAINT FK_PARENTESCO_FAM FOREIGN KEY (ID_PARENTESCO) REFERENCES PARENTESCO (ID_PARENTESCO),
	CONSTRAINT FK_DIRECCION_EMER FOREIGN KEY (ID_DIRECCION_EMER) REFERENCES DIRECCION(ID_DIRECCION)
);
-- TABLA EMPLEADOS
CREATE TABLE EMPLEADOS (
    ID_EMPLEADO INT NOT NULL,
    ID_CARGO INT,
    ID_PERSONA INT,
	ID_ESTADO_CIVIL INT,
	ID_CONTACTO_EMER INT,
	ADJ_DOC BLOB,
    SALARIO NUMBER,
	CONSTRAINT PK_EMPLEADO PRIMARY KEY (ID_EMPLEADO),
    CONSTRAINT FK_CARGO_EMPL FOREIGN KEY (ID_CARGO) REFERENCES CARGO(ID_CARGO),
    CONSTRAINT FK_PERSONA_EMPL FOREIGN KEY (ID_PERSONA) REFERENCES PERSONA(ID_PERSONA),
	CONSTRAINT FK_ESTADO_CIVIL FOREIGN KEY (ID_ESTADO_CIVIL) REFERENCES ESTADO_CIVIL (ID_ESTADO_CIVIL),
	CONSTRAINT FK_CONTACTO_EMERG FOREIGN KEY (ID_CONTACTO_EMER) REFERENCES CONTACTO_EMERGENGIA (ID_CONTACTO_EMER)
);

-----TABLA DE VENDEDOR DEL PROVEEDOR
CREATE TABLE VENDEDOR(
    ID_VENDEDOR INT NOT NULL,
	P_NOMBRE VARCHAR(50),
    S_NOMBRE VARCHAR(50),
    P_APELLIDO VARCHAR(50),
    S_APELLIDO VARCHAR(50),
	FECHA_NACIMIEMTO DATE,
    NUM_DNI VARCHAR(20) UNIQUE NOT NULL,
	RTN VARCHAR (14) UNIQUE, 
	ID_TEL INT,
	ID_DIRECCION INT,
	CORREO VARCHAR (100) UNIQUE,
    CONSTRAINT PK_VENDEDOR PRIMARY KEY (ID_VENDEDOR),
    CONSTRAINT FK_TELEFONO_VENDEDOR FOREIGN KEY (ID_TEL) REFERENCES TELEFONO(ID_TEL),
	CONSTRAINT FK_DIRECCION_ESPECI_VENDEDOR FOREIGN KEY (ID_DIRECCION) REFERENCES DIRECCION(ID_DIRECCION)
);

---- TABLA DE PROVEEDORES
CREATE TABLE PROVEEDOR (
	ID_PROVEEDOR INT,
	NOM_PROVEEDOR VARCHAR(255) NOT NULL,
	ID_DIRECCION INT,
	RTN VARCHAR (14) UNIQUE, 
	ID_TEL INT,
	CORREO VARCHAR (100) UNIQUE,
	ID_VENDEDOR INT, --INFORMACI�N DEL VENDEDOR
	ADJ_DOC BLOB,
	CONSTRAINT PK_PROVEEDOR  PRIMARY KEY (ID_PROVEEDOR),
	CONSTRAINT FK_DIRECCION_PROVEEDOR FOREIGN KEY (ID_DIRECCION) REFERENCES DIRECCION(ID_DIRECCION),
	CONSTRAINT FK_TELEFONO_PROVEEDOR FOREIGN KEY (ID_TEL) REFERENCES TELEFONO(ID_TEL),
    CONSTRAINT FK_VENDEDOR FOREIGN KEY (ID_VENDEDOR) REFERENCES VENDEDOR(ID_VENDEDOR)
);


----TABLA DE LAS CATEGORIAS DEL PRODUCTO
CREATE TABLE CATEGORIAS (
	ID_CATEGORIA INT,
	NOM_CATEGORIA VARCHAR (255),
	CONSTRAINT PK_CATEGORIA PRIMARY KEY (ID_CATEGORIA)
);

--- TABLA DEL TIPO DE MONEDA
CREATE TABLE TIPO_MONEDA (
	ID_MONEDA INT,
	NOM_MONEDA VARCHAR(255),
	CONSTRAINT PK_MONEDA PRIMARY KEY (ID_MONEDA)
);

-- TABLA PRODUCTOS
CREATE TABLE REPUESTOS (
    ID_REPUESTO INT NOT NULL,
	ID_CATEGORIA INT,
	ID_MONEDA INT,
	NOM_PRODUCTO VARCHAR(255),
    DESCRIPCION VARCHAR(255),
    COSTO_ADQUISICION NUMBER(10, 2),
    COSTO_VENTA NUMBER(10, 2),
	PRECIO_UNITARIO NUMBER(10, 2),
    CANTIDAD INT,
	NUM_FACT INT,
	ADJ_DOC_FAC BLOB, --ADJUNTAR LA FACTURA
	CONSTRAINT PK_PRODUCTO PRIMARY KEY (ID_REPUESTO),
	CONSTRAINT FK_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS (ID_CATEGORIA),
	CONSTRAINT FK_TIP_MONEDA FOREIGN KEY (ID_MONEDA) REFERENCES TIPO_MONEDA (ID_MONEDA)
);

-- TABLA INVENTARIO
CREATE TABLE INVENTARIO (
ID_INVENTARIO INT PRIMARY KEY NOT NULL,
CANTIDAD_PRODUCTOS INT,
FECHA_ENTRADA VARCHAR (50),
FECHA_SALIDA VARCHAR (50),
ID_REPUESTO INT,
CONSTRAINT FK_PRODUCT FOREIGN KEY (ID_REPUESTO) REFERENCES REPUESTOS (ID_REPUESTO)	
);

---TABLA DE LA VERSION DEL AUTO
CREATE TABLE VERSION_C (
    ID_VERSION INT NOT NULL,
    NOMBRE_VERSION VARCHAR(50),
    CONSTRAINT PK_VERSION PRIMARY KEY (ID_VERSION)
);

---TABLADEL MODELO DEL AUTO
CREATE TABLE MODELO(
ID_MODELO INT NOT NULL,
ID_VERSION INT,
NOM_MODELO VARCHAR (50),
CONSTRAINT PK_MODELO PRIMARY KEY (ID_MODELO),
CONSTRAINT FK_VERSION FOREIGN KEY (ID_VERSION) REFERENCES VERSION_C (ID_VERSION)
);

---TABLA DEL PAIS DE ENSAMBLAJE DEL AUTO
CREATE TABLE PAIS_EMSAMBLAJE(
    ID_ENSAMBLAJE INT NOT NULL,
    NOMBRE_PAIS_ENSAMBLAJE VARCHAR(50),
    CONSTRAINT PK_PAIS_EMSA PRIMARY KEY (ID_ENSAMBLAJE)
);

---- TABLA DE LA MARCA DEL AUTO
CREATE TABLE MARCA(
    ID_MARCA NCHAR(5) NOT NULL,
    ID_MODELO INT,
    ID_ENSAMBLAJE INT,
    NOM_MARCA VARCHAR (50),
    CONSTRAINT PK_MARCA PRIMARY KEY (ID_MARCA),
    CONSTRAINT FK_MODELO FOREIGN KEY (ID_MODELO) REFERENCES MODELO(ID_MODELO),
    CONSTRAINT FK_PAIS_EMSAMBLAJE FOREIGN KEY (ID_ENSAMBLAJE) REFERENCES PAIS_EMSAMBLAJE(ID_ENSAMBLAJE)
);

----TABLA DEL COLOR DEL AUTO
CREATE TABLE COLOR(
ID_COLOR INT NOT NULL,
NOM_COLOR VARCHAR (50),
CONSTRAINT PK_COLOR PRIMARY KEY (ID_COLOR)
);

--TABLA DEL TIPO DE COMBUSTIBLE DEL AUTO
CREATE TABLE TIPO_COMBUSTIBLE(
ID_TIPO_COMBUSTIBLE NCHAR(5) NOT NULL,
NOM_COMBUSTIBLE VARCHAR (50),
CONSTRAINT PK_COMBUSTIBLE PRIMARY KEY (ID_TIPO_COMBUSTIBLE)
);

---- TABLA DE LOS VEHICULOS(AUTOS)
CREATE TABLE VEHICULO (
ID_NUM_PLACA NCHAR(7) PRIMARY KEY NOT NULL,
ID_MARCA NCHAR(5),
ID_COLOR INT,
ID_TIPO_COMBUSTIBLE NCHAR(5),
ANIO INT,
CONSTRAINT FK_MARCA FOREIGN KEY (ID_MARCA) REFERENCES MARCA (ID_MARCA),
CONSTRAINT FK_COLOR FOREIGN KEY (ID_COLOR) REFERENCES COLOR (ID_COLOR) ,
CONSTRAINT FK_COMBUSTIBLE FOREIGN KEY (ID_TIPO_COMBUSTIBLE) REFERENCES TIPO_COMBUSTIBLE (ID_TIPO_COMBUSTIBLE) 
);

-- TABLA SERVICIO
CREATE TABLE SERVICIO (
    ID_SERVICIO INT NOT NULL,
    NOMBRE_SERVICIO VARCHAR(255),
	CONSTRAINT PK_SERVICIO PRIMARY KEY (ID_SERVICIO)
);

-- TABLA COTIZACION
CREATE TABLE COTIZACION (
   	 ID_COTIZACION INT PRIMARY KEY NOT NULL,
   	 ID_CLIENTE INT,
     ID_EMPRESA INT,
	 ID_NUM_PLACA NCHAR(7),
	 ID_SERVICIO INT,
	 ID_REPUESTO INT,
  	 CANTIDAD_MATERIALES INT,
	 FECHA_COTIZACION DATE,
	 FECHA_VENCIMIENTO_COTIZACION DATE,
	 DIAGNOSTICO VARCHAR(500),
	 DESCUENTO DECIMAL(10, 2),
     ISV DECIMAL(10, 2),
     TOTAL DECIMAL(10, 2),
     SUBTOTAL DECIMAL(10, 2),
     CONSTRAINT FK_CLIE_NAT FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE_NATURAL (ID_CLIENTE),
	 CONSTRAINT FK_CLIE_EMPRESA FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA (ID_EMPRESA),
     CONSTRAINT FK_SERVICIOS FOREIGN KEY (ID_SERVICIO) REFERENCES SERVICIO(ID_SERVICIO),
	 CONSTRAINT FK_VEHICULO FOREIGN KEY (ID_NUM_PLACA) REFERENCES VEHICULO (ID_NUM_PLACA),
	 CONSTRAINT FK_REPESTOS FOREIGN KEY (ID_REPUESTO) REFERENCES REPUESTOS (ID_REPUESTO)	
);

CREATE TABLE EMPLEADO_X_SERVICIO (
    ID_EMPLEADO INT NOT NULL,
    ID_SERVICIO INT NOT NULL,
    CONSTRAINT FK_EMPL FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO),
    CONSTRAINT FK_SERVI FOREIGN KEY (ID_SERVICIO) REFERENCES SERVICIO(ID_SERVICIO)
);

-- TABLA ORDEN SERVICIO
CREATE TABLE ORDEN_SERVICIO (
  	 ID_ORDEN_SERVICIO INT NOT NULL,
     ID_EMPLEADO INT,
   	 FECHA_ORDEN DATE,
	 FECHA_ENTRADA DATE,
	 FECHA_SALIDA DATE,
   	 ID_COTIZACION INT,
	 OBSERVACIONES VARCHAR(1000),
	 CONSTRAINT PK_ORDEN PRIMARY KEY (ID_ORDEN_SERVICIO),
   	 CONSTRAINT FK_EMPLEAD FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO),
   	 CONSTRAINT FK_COTIZ FOREIGN KEY (ID_COTIZACION) REFERENCES COTIZACION(ID_COTIZACION)
);

-- TABLA METODO_PAGO
CREATE TABLE METODO_PAGO (
    ID_MET_PAGO INT NOT NULL,
    NOMBRE_METODO VARCHAR(255),
	CONSTRAINT PK_MET_PAG PRIMARY KEY (ID_MET_PAGO)
);

CREATE TABLE REGISTRO_CAI (
    ID_CAI INT NOT NULL,
    NUM_CAI VARCHAR(20),
    FECHA_AUTORIZACION DATE,
    FECHA_VENCIMIENTO DATE,
    RANGO_INICIO INT,
    RANGO_FIN INT,
	CONSTRAINT PK_CAI PRIMARY KEY (ID_CAI)
);

---- TABALA DE FACTURA 
CREATE TABLE FACTURA (
	ID_FACTURA INT NOT NULL,
    ID_COTIZACION INT,
    ID_CLIENTE INT,
    ID_EMPRESA INT,
    ID_CAI INT,
	ID_EMPLEADO INT,
	ID_MET_PAGO INT,
    FECHA DATE,
	CONSTRAINT PK_FACTURA PRIMARY KEY (ID_FACTURA),
	CONSTRAINT FK_FACT_COTIZ FOREIGN KEY (ID_COTIZACION) REFERENCES COTIZACION (ID_COTIZACION),
    CONSTRAINT FK_CLIENTE_FAC FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE_NATURAL (ID_CLIENTE),
    CONSTRAINT FK_EMPRESA_FACTU FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA (ID_EMPRESA),
	CONSTRAINT FK_EMPLEA FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO),
    CONSTRAINT FK_METODO_PAG FOREIGN KEY (ID_MET_PAGO) REFERENCES METODO_PAGO(ID_MET_PAGO),
	CONSTRAINT FK_CAI FOREIGN KEY (ID_CAI) REFERENCES REGISTRO_CAI(ID_CAI)
);

--TABLA DE DETALLE DE FACTURA 
CREATE TABLE DETALLE_FACTURA(
    ID_DETALLE_FACTURA INT NOT NULL,
    ID_FACTURA INT,
    ID_ORDEN_SERVICIO INT,
    CONSTRAINT PK_DETALLE_FACTURA PRIMARY KEY (ID_DETALLE_FACTURA),
    CONSTRAINT FK_FACTURA_D FOREIGN KEY (ID_FACTURA) REFERENCES FACTURA(ID_FACTURA),
    CONSTRAINT FK_ORDEN_DETALLE FOREIGN KEY (ID_ORDEN_SERVICIO) REFERENCES ORDEN_SERVICIO(ID_ORDEN_SERVICIO)
);

---TABLA DE DETALLE COTIZACION
CREATE TABLE DETALLE_COTIZACION(
    ID_DETALLE_COTIZACION INT NOT NULL,
    ID_COTIZACION INT,
    ID_INVENTARIO INT,
    CATIDAD INT,
    CONSTRAINT PK_DETALLE_COTIZACION PRIMARY KEY (ID_DETALLE_COTIZACION),
    CONSTRAINT FK_COTIZACION_D FOREIGN KEY (ID_COTIZACION) REFERENCES COTIZACION(ID_COTIZACION),
    CONSTRAINT FK_INVENTARIO_DETALLE FOREIGN KEY (ID_INVENTARIO) REFERENCES INVENTARIO(ID_INVENTARIO)
);