-- Provedores
INSERT INTO proveedor (id_proveedor, nom_proveedor, id_direccion, rtn, id_tel, correo, id_vendedor, adj_doc)
VALUES (1, 'Proveedor 1', 100, 'RTN1', 1234567890, 'proveedor1@example.com', 10, NULL);

INSERT INTO proveedor (id_proveedor, nom_proveedor, id_direccion, rtn, id_tel, correo, id_vendedor, adj_doc)
VALUES (2, 'Proveedor 2', 101, 'RTN2', 2345678901, 'proveedor2@example.com', 11, NULL);

INSERT INTO proveedor (id_proveedor, nom_proveedor, id_direccion, rtn, id_tel, correo, id_vendedor, adj_doc)
VALUES (3, 'Proveedor 3', 102, 'RTN3', 3456789012, 'proveedor3@example.com', 12, NULL);

-- Tabla Departamento
INSERT ALL
INTO DEPARTAMENTO (ID_DEPARTAMENTO, NOMBRE_DEPARTAMENTO) VALUES (1, 'Atlántida')
INTO DEPARTAMENTO (ID_DEPARTAMENTO, NOMBRE_DEPARTAMENTO) VALUES (2, 'Colón')
INTO DEPARTAMENTO (ID_DEPARTAMENTO, NOMBRE_DEPARTAMENTO) VALUES (3, 'Comayagua')
INTO DEPARTAMENTO (ID_DEPARTAMENTO, NOMBRE_DEPARTAMENTO) VALUES (4, 'Copán')
INTO DEPARTAMENTO (ID_DEPARTAMENTO, NOMBRE_DEPARTAMENTO) VALUES (5, 'Cortés')
SELECT * FROM dual;

-- Tabla Municipio
INSERT ALL
INTO MUNICIPIO (ID_MUNICIPIO, NOMBRE_MUNICIPIO, ID_DEPARTAMENTO) VALUES (1, 'La Ceiba', 1)
INTO MUNICIPIO (ID_MUNICIPIO, NOMBRE_MUNICIPIO, ID_DEPARTAMENTO) VALUES (2, 'Tela', 1)
INTO MUNICIPIO (ID_MUNICIPIO, NOMBRE_MUNICIPIO, ID_DEPARTAMENTO) VALUES (3, 'Trujillo', 1)
INTO MUNICIPIO (ID_MUNICIPIO, NOMBRE_MUNICIPIO, ID_DEPARTAMENTO) VALUES (4, 'Balfate', 1)
INTO MUNICIPIO (ID_MUNICIPIO, NOMBRE_MUNICIPIO, ID_DEPARTAMENTO) VALUES (5, 'Irraías', 2)
SELECT * FROM dual;

-- Tabla Ciudad
INSERT ALL
INTO CIUDAD (ID_CIUDAD, NOMBRE_CIUDAD, ID_MUNICIPIO) VALUES (1, 'Centro', 1)
INTO CIUDAD (ID_CIUDAD, NOMBRE_CIUDAD, ID_MUNICIPIO) VALUES (2, 'Barrio El Iman', 1)
INTO CIUDAD (ID_CIUDAD, NOMBRE_CIUDAD, ID_MUNICIPIO) VALUES (3, 'Barrio Las Brisas', 2)
INTO CIUDAD (ID_CIUDAD, NOMBRE_CIUDAD, ID_MUNICIPIO) VALUES (4, 'Barrio El Porvenir', 3)
INTO CIUDAD (ID_CIUDAD, NOMBRE_CIUDAD, ID_MUNICIPIO) VALUES (5, 'Barrio Los Maestros', 4)
SELECT * FROM dual;

--Table TELEFONO
INSERT ALL
INTO TELEFONO (ID_TEL, NUM_TEL) VALUES (1, '9999-9999')
INTO TELEFONO (ID_TEL, NUM_TEL) VALUES (2, '8888-8888')
INTO TELEFONO (ID_TEL, NUM_TEL) VALUES (3, '7777-7777')
SELECT * FROM dual;

-- Tabla DIRECCION
INSERT ALL
INTO DIRECCION (ID_DIRECCION, DIRECCION, ID_CIUDAD) VALUES (1, 'Col. San Rafael, Casa #5', 1)
INTO DIRECCION (ID_DIRECCION, DIRECCION, ID_CIUDAD) VALUES (2, 'Barrio Las Delicias, Casa #10', 2)
INTO DIRECCION (ID_DIRECCION, DIRECCION, ID_CIUDAD) VALUES (3, 'Col. Moderna, Casa #15', 3)
SELECT * FROM dual;

-- Tabla PERSONA
ALTER TABLE PERSONA
MODIFY RTN VARCHAR2(15);

INSERT ALL
INTO PERSONA (ID_PERSONA, P_NOMBRE, S_NOMBRE, P_APELLIDO, S_APELLIDO, FECHA_NACIMIEMTO, NUM_DNI, RTN, ID_TEL, ID_DIRECCION, CORREO) VALUES (1, 'Juan', 'Carlos', 'López', 'García', TO_DATE('1990-05-15', 'YYYY-MM-DD'), '0501-1990-12345', '0801-1990-12345', 1, 1, 'juan@example.com')
INTO PERSONA (ID_PERSONA, P_NOMBRE, S_NOMBRE, P_APELLIDO, S_APELLIDO, FECHA_NACIMIEMTO, NUM_DNI, RTN, ID_TEL, ID_DIRECCION, CORREO) VALUES (2, 'María', NULL, 'Martínez', 'Pérez', TO_DATE('1985-09-20', 'YYYY-MM-DD'), '0601-1985-54321', NULL, 2, 2, 'maria@example.com')
SELECT * FROM dual;

--!OJO AQUI esta tabla da errores y se tiene que ejecutar uno a uno
-- Tabla Tipo CLIENTE
INSERT INTO TIPO_CLIENTE (ID_TIPO, TIPO_CLIE) VALUES (1, 'Natural');
INSERT INTO TIPO_CLIENTE (ID_TIPO, TIPO_CLIE) VALUES (2, 'Juridico');

-- Tabla CLIENTE_NATURAL
INSERT ALL
INSERT INTO CLIENTE_NATURAL (ID_CLIENTE, ID_PERSONA, ID_TIPO) VALUES (1, 1, 1)
INSERT INTO CLIENTE_NATURAL (ID_CLIENTE, ID_PERSONA, ID_TIPO) VALUES (2, 2, 1)
SELECT * FROM dual;

-- Tabla de Empresa
ALTER TABLE EMPRESA DROP CONSTRAINT FK_TIPO_CLIENTE;
INSERT ALL
INTO EMPRESA (ID_EMPRESA, ID_TIPO, NOM_EMPRESA, ID_DIRECCION, RTN, ID_TEL, CORREO) VALUES (1, 2, 'Empresa ABC', 3, '0801-1234567', 3, 'info@empresaabc.com')
INTO EMPRESA (ID_EMPRESA, ID_TIPO, NOM_EMPRESA, ID_DIRECCION, RTN, ID_TEL, CORREO) VALUES (2, 2, 'Empresa XYZ', 2, '0801-9876543', 2, 'contacto@empresaxyz.com')
SELECT * FROM dual;

-- Tabla Contacto_Empresa 
INSERT ALL
INTO CONTACTO_EMPRESA (ID_CONTACTO_EMP, ID_EMPRESA, P_NOMBRE, S_NOMBRE, P_APELLIDO, S_APELLIDO, FECHA_NACIMIEMTO, NUM_DNI, RTN, ID_TEL, ID_DIRECCION, RAZON_SOCIAL, CORREO) VALUES (1, 1, 'Roberto', 'Carlos', 'Pérez', 'López', TO_DATE('1980-03-10', 'YYYY-MM-DD'), '0501-1980-54321', NULL, 1, 1, 'Contador', 'roberto@example.com')
INTO CONTACTO_EMPRESA (ID_CONTACTO_EMP, ID_EMPRESA, P_NOMBRE, S_NOMBRE, P_APELLIDO, S_APELLIDO, FECHA_NACIMIEMTO, NUM_DNI, RTN, ID_TEL, ID_DIRECCION, RAZON_SOCIAL, CORREO) VALUES (2, 1, 'Laura', NULL, 'Gómez', 'Hernández', TO_DATE('1975-07-20', 'YYYY-MM-DD'), '0601-1975-12345', NULL, 3, 3, 'Gerente de Ventas', 'laura@example.com')
SELECT * FROM dual;

-- Tabla Cargo 
INSERT ALL
INTO CARGO (ID_CARGO, NOMBRE_CARGO) VALUES (1, 'Gerente')
INTO CARGO (ID_CARGO, NOMBRE_CARGO) VALUES (2, 'Contador')
INTO CARGO (ID_CARGO, NOMBRE_CARGO) VALUES (3, 'Asistente Administrativo')
SELECT * FROM dual;

-- Tabla ESTADO_CIVIL
INSERT ALL
INTO ESTADO_CIVIL (ID_ESTADO_CIVIL, ESTADO) VALUES (1, 'Soltero/a')
INTO ESTADO_CIVIL (ID_ESTADO_CIVIL, ESTADO) VALUES (2, 'Casado/a')
INTO ESTADO_CIVIL (ID_ESTADO_CIVIL, ESTADO) VALUES (3, 'Divorciado/a')
SELECT * FROM dual;

-- Tabla PARENTESCO
INSERT ALL
INTO PARENTESCO (ID_PARENTESCO, TIPO) VALUES (1, 'Padre')
INTO PARENTESCO (ID_PARENTESCO, TIPO) VALUES (2, 'Madre')
INTO PARENTESCO (ID_PARENTESCO, TIPO) VALUES (3, 'Hermano')
INTO PARENTESCO (ID_PARENTESCO, TIPO) VALUES (4, 'Hermana')
SELECT * FROM dual;

-- Tabla CONTACTO_EMERGENGIA
INSERT ALL
INTO CONTACTO_EMERGENGIA (ID_CONTACTO_EMER, NOM_CONTACTO_EMER, TEL_CONTACTO_EMER, ID_PARENTESCO, ID_DIRECCION_EMER) VALUES (1, 'Carlos Pérez', 1, 1, 2);
INTO CONTACTO_EMERGENGIA (ID_CONTACTO_EMER, NOM_CONTACTO_EMER, TEL_CONTACTO_EMER, ID_PARENTESCO, ID_DIRECCION_EMER) VALUES (2, 'Ana Gómez', 2, 2, 3);
SELECT * FROM dual;

-- Tabla EMPLEADOS
INSERT ALL
INTO EMPLEADOS (ID_EMPLEADO, ID_CARGO, ID_PERSONA, ID_ESTADO_CIVIL, ID_CONTACTO_EMER, SALARIO) VALUES (1, 1, 1, 2, 1, 25000.00)
INTO EMPLEADOS (ID_EMPLEADO, ID_CARGO, ID_PERSONA, ID_ESTADO_CIVIL, ID_CONTACTO_EMER, SALARIO) VALUES (2, 3, 2, 1, 2, 18000.00)
SELECT * FROM dual;

-- Tipo de VERSION_C
INSERT ALL
INTO VERSION_C (ID_VERSION, NOMBRE_VERSION) VALUES (1, 'Standard')
INTO VERSION_C (ID_VERSION, NOMBRE_VERSION) VALUES (2, 'Deluxe')
INTO VERSION_C (ID_VERSION, NOMBRE_VERSION) VALUES (3, 'Premium')
SELECT * FROM dual;

-- Tabla de PAIS_EMSAMBLAJE
INSERT ALL
INTO PAIS_EMSAMBLAJE (ID_ENSAMBLAJE, NOMBRE_PAIS_ENSAMBLAJE) VALUES (1, 'Japón')
INTO PAIS_EMSAMBLAJE (ID_ENSAMBLAJE, NOMBRE_PAIS_ENSAMBLAJE) VALUES (2, 'Estados Unidos')
INTO PAIS_EMSAMBLAJE (ID_ENSAMBLAJE, NOMBRE_PAIS_ENSAMBLAJE) VALUES (3, 'Alemania')
SELECT * FROM dual;

-- Tabla Modelo 
INSERT ALL
INTO MODELO (ID_MODELO, ID_VERSION, NOM_MODELO) VALUES (1, 1, 'Corolla')
INTO MODELO (ID_MODELO, ID_VERSION, NOM_MODELO) VALUES (2, 2, 'Civic')
INTO MODELO (ID_MODELO, ID_VERSION, NOM_MODELO) VALUES (3, 3, 'Fiesta')
SELECT * FROM dual;

-- Tabla de MARCA
INSERT ALL
INTO MARCA (ID_MARCA, ID_MODELO, ID_ENSAMBLAJE, NOM_MARCA) VALUES (1, 1, 1, 'Toyota')
INTO MARCA (ID_MARCA, ID_MODELO, ID_ENSAMBLAJE, NOM_MARCA) VALUES (2, 2, 1, 'Honda')
SELECT * FROM dual;

-- Tabla COLOR 
INSERT ALL
INTO COLOR (ID_COLOR, NOM_COLOR) VALUES (1, 'Rojo')
INTO COLOR (ID_COLOR, NOM_COLOR) VALUES (2, 'Azul')
INTO COLOR (ID_COLOR, NOM_COLOR) VALUES (3, 'Negro')
SELECT * FROM dual;

-- Tabla TIPO_COMBUSTIBLE
INSERT ALL
INTO TIPO_COMBUSTIBLE (ID_TIPO_COMBUSTIBLE, NOM_COMBUSTIBLE) VALUES ('GASOL', 'Gasolina')
INTO TIPO_COMBUSTIBLE (ID_TIPO_COMBUSTIBLE, NOM_COMBUSTIBLE) VALUES ('DIESE', 'Diésel')
INTO TIPO_COMBUSTIBLE (ID_TIPO_COMBUSTIBLE, NOM_COMBUSTIBLE) VALUES ('HIBRI', 'Híbrido')
SELECT * FROM dual;

-- Tabla VEHICULO
INSERT ALL
INTO VEHICULO (ID_NUM_PLACA, ID_MARCA, ID_COLOR, ID_TIPO_COMBUSTIBLE, ANIO) VALUES ('PQW123', 1, 1, 'GASOL', 2023)
INTO VEHICULO (ID_NUM_PLACA, ID_MARCA, ID_COLOR, ID_TIPO_COMBUSTIBLE, ANIO) VALUES ('ABC456', 2, 2, 'GASOL', 2022)
INTO VEHICULO (ID_NUM_PLACA, ID_MARCA, ID_COLOR, ID_TIPO_COMBUSTIBLE, ANIO) VALUES ('XYZ789', 1, 3, 'DIESE', 2024)
SELECT * FROM dual;

-- Tabla SERVICIO
INSERT ALL
INTO SERVICIO (ID_SERVICIO, NOMBRE_SERVICIO) VALUES (1, 'Cambio de aceite')
INTO SERVICIO (ID_SERVICIO, NOMBRE_SERVICIO) VALUES (2, 'Revisión de frenos')
INTO SERVICIO (ID_SERVICIO, NOMBRE_SERVICIO) VALUES (3, 'Alineación y balanceo')
SELECT * FROM dual;

-- Tabla COTIZACION
INSERT ALL
INTO COTIZACION (ID_COTIZACION, ID_CLIENTE, ID_EMPRESA, ID_NUM_PLACA, ID_SERVICIO, CANTIDAD_MATERIALES, FECHA_COTIZACION, FECHA_VENCIMIENTO_COTIZACION, DIAGNOSTICO, DESCUENTO, ISV, TOTAL, SUBTOTAL) VALUES (1, 1, 1, 'PQW123', 1, 2, TO_DATE('2024-04-20', 'YYYY-MM-DD'), TO_DATE('2024-04-25', 'YYYY-MM-DD'), 'Cambio de aceite y filtro', 0, 15, 250.00, 250.00)
INTO COTIZACION (ID_COTIZACION, ID_CLIENTE, ID_EMPRESA, ID_NUM_PLACA, ID_SERVICIO, CANTIDAD_MATERIALES, FECHA_COTIZACION, FECHA_VENCIMIENTO_COTIZACION, DIAGNOSTICO, DESCUENTO, ISV, TOTAL, SUBTOTAL) VALUES (2, 2, 2, 'ABC456', 2, 1, TO_DATE('2024-04-20', 'YYYY-MM-DD'), TO_DATE('2024-04-25', 'YYYY-MM-DD'), 'Revisión de frenos', 10, 15, 180.00, 180.00)
SELECT * FROM dual;

-- Tabla EMPLEADO_X_SERVICIO
INSERT ALL
INTO EMPLEADO_X_SERVICIO (ID_EMPLEADO, ID_SERVICIO) VALUES (1, 1)
INTO EMPLEADO_X_SERVICIO (ID_EMPLEADO, ID_SERVICIO) VALUES (2, 2)
SELECT * FROM dual;

-- Tabla ORDEN_SERVICIO
INSERT ALL
INTO ORDEN_SERVICIO (ID_ORDEN_SERVICIO, ID_EMPLEADO, FECHA_ORDEN, FECHA_ENTRADA, FECHA_SALIDA, ID_COTIZACION, OBSERVACIONES) VALUES (1, 1, TO_DATE('2024-04-20', 'YYYY-MM-DD'), TO_DATE('2024-04-25', 'YYYY-MM-DD'), TO_DATE('2024-04-25', 'YYYY-MM-DD'), 1, 'Servicio completado exitosamente')
INTO ORDEN_SERVICIO (ID_ORDEN_SERVICIO, ID_EMPLEADO, FECHA_ORDEN, FECHA_ENTRADA, FECHA_SALIDA, ID_COTIZACION, OBSERVACIONES) VALUES (2, 2, TO_DATE('2024-04-20', 'YYYY-MM-DD'), TO_DATE('2024-04-25', 'YYYY-MM-DD'), TO_DATE('2024-04-25', 'YYYY-MM-DD'), 2, 'Revisión de frenos realizada')
SELECT * FROM dual;

-- Tabla METODO_PAGO
INSERT ALL
INTO METODO_PAGO (ID_MET_PAGO, NOMBRE_METODO) VALUES (1, 'Efectivo')
INTO METODO_PAGO (ID_MET_PAGO, NOMBRE_METODO) VALUES (2, 'Tarjeta de crédito')
INTO METODO_PAGO (ID_MET_PAGO, NOMBRE_METODO) VALUES (3, 'Transferencia bancaria')
SELECT * FROM dual;

-- REGISTRO_CAI
INSERT ALL
INTO REGISTRO_CAI (ID_CAI, NUM_CAI, FECHA_AUTORIZACION, FECHA_VENCIMIENTO, RANGO_INICIO, RANGO_FIN) VALUES (1, '12345678901234567890', TO_DATE('2024-01-01', 'YYYY-MM-DD'), TO_DATE('2024-12-31', 'YYYY-MM-DD'), 100000, 199999)
SELECT * FROM dual;

-- Tabla FACTURA
INSERT ALL
INTO FACTURA (ID_FACTURA, ID_COTIZACION, ID_CLIENTE, ID_EMPRESA, ID_CAI, ID_EMPLEADO, ID_MET_PAGO, FECHA) VALUES (1, 1, 1, 1, 1, 1, 1, TO_DATE('2024-04-25', 'YYYY-MM-DD'))
INTO FACTURA (ID_FACTURA, ID_COTIZACION, ID_CLIENTE, ID_EMPRESA, ID_CAI, ID_EMPLEADO, ID_MET_PAGO, FECHA) VALUES (2, 2, 2, 2, 1, 2, 1, TO_DATE('2024-04-25', 'YYYY-MM-DD'))
SELECT * FROM dual;

-- Tabla DETALLE_FACTURA
INSERT ALL
INTO DETALLE_FACTURA (ID_DETALLE_FACTURA, ID_FACTURA, ID_ORDEN_SERVICIO) VALUES (1, 1, 1)
INTO DETALLE_FACTURA (ID_DETALLE_FACTURA, ID_FACTURA, ID_ORDEN_SERVICIO) VALUES (2, 2, 2)
SELECT * FROM dual;

-- Tipo MONEDA
INSERT ALL
INTO TIPO_MONEDA (ID_MONEDA, NOM_MONEDA) VALUES (1, 'Lempira (HNL)')
INTO TIPO_MONEDA (ID_MONEDA, NOM_MONEDA) VALUES (2, 'Dólar estadounidense (USD)')
INTO TIPO_MONEDA (ID_MONEDA, NOM_MONEDA) VALUES (3, 'Euro (EUR)')
INTO TIPO_MONEDA (ID_MONEDA, NOM_MONEDA) VALUES (4, 'Libra esterlina (GBP)')
INTO TIPO_MONEDA (ID_MONEDA, NOM_MONEDA) VALUES (5, 'Peso mexicano (MXN)')
SELECT * FROM dual;

-- Tabla CATEGORIA
INSERT ALL
INTO CATEGORIAS (ID_CATEGORIA, NOM_CATEGORIA) VALUES (1, 'Filtros')
INTO CATEGORIAS (ID_CATEGORIA, NOM_CATEGORIA) VALUES (2, 'Frenos')
INTO CATEGORIAS (ID_CATEGORIA, NOM_CATEGORIA) VALUES (3, 'Suspensión')
INTO CATEGORIAS (ID_CATEGORIA, NOM_CATEGORIA) VALUES (4, 'Motor')
INTO CATEGORIAS (ID_CATEGORIA, NOM_CATEGORIA) VALUES (5, 'Electricidad')
SELECT * FROM dual;

-- Tabla REPUESTOS
INSERT ALL
INTO REPUESTOS (ID_REPUESTO, ID_CATEGORIA, ID_MONEDA, NOM_PRODUCTO, DESCRIPCION, COSTO_ADQUISICION, COSTO_VENTA, PRECIO_UNITARIO, CANTIDAD, NUM_FACT) VALUES (1, 1, 1, 'Filtro de aceite', 'Filtro de aceite para automóviles', 5.00, 10.00, 15.00, 100, 123456)
INTO REPUESTOS (ID_REPUESTO, ID_CATEGORIA, ID_MONEDA, NOM_PRODUCTO, DESCRIPCION, COSTO_ADQUISICION, COSTO_VENTA, PRECIO_UNITARIO, CANTIDAD, NUM_FACT) VALUES (2, 2, 2, 'Pastillas de freno', 'Pastillas de freno para automóviles', 20.00, 30.00, 40.00, 50, 654321)
SELECT * FROM dual;

-- Tabla INVENTARIO
INSERT ALL
INTO INVENTARIO (ID_INVENTARIO, CANTIDAD_PRODUCTOS, FECHA_ENTRADA, FECHA_SALIDA, ID_REPUESTO) VALUES (1, 50, TO_DATE('2024-04-20', 'YYYY-MM-DD'), TO_DATE('2024-04-25', 'YYYY-MM-DD'), 1)
INTO INVENTARIO (ID_INVENTARIO, CANTIDAD_PRODUCTOS, FECHA_ENTRADA, FECHA_SALIDA, ID_REPUESTO) VALUES (2, 30, TO_DATE('2024-04-20', 'YYYY-MM-DD'), TO_DATE('2024-04-25', 'YYYY-MM-DD'), 2)
SELECT * FROM dual;

-- Table CONTIZACION
INSERT ALL
INTO DETALLE_COTIZACION (ID_DETALLE_COTIZACION, ID_COTIZACION, ID_INVENTARIO, CATIDAD) VALUES (1, 1, 1, 2)
SELECT * FROM dual;

-- Tabla VENDEDOR
INSERT ALL
INTO VENDEDOR (ID_VENDEDOR, P_NOMBRE, S_NOMBRE, P_APELLIDO, S_APELLIDO, FECHA_NACIMIEMTO, NUM_DNI, RTN, ID_TEL, ID_DIRECCION, CORREO) VALUES (1, 'Juan', 'Carlos', 'Gómez', 'Pérez', TO_DATE('1990-05-15', 'YYYY-MM-DD'), '1234567890123', '0801-3333333', 1, 1, 'juancarlos@vendedor.com')
INTO VENDEDOR (ID_VENDEDOR, P_NOMBRE, S_NOMBRE, P_APELLIDO, S_APELLIDO, FECHA_NACIMIEMTO, NUM_DNI, RTN, ID_TEL, ID_DIRECCION, CORREO) VALUES (2, 'María', NULL, 'López', 'Martínez', TO_DATE('1985-09-20', 'YYYY-MM-DD'), '9876543210987', '0801-4444444', 2, 2, 'marialopez@vendedor.com')
SELECT * FROM dual;


-- Tabla Proveedor
INSERT ALL
INTO PROVEEDOR (ID_PROVEEDOR, NOM_PROVEEDOR, ID_DIRECCION, RTN, ID_TEL, CORREO, ID_VENDEDOR) VALUES (1, 'Proveedor A', 1, '0801-1111111', 1, 'info@proveedora.com', 1)
INTO PROVEEDOR (ID_PROVEEDOR, NOM_PROVEEDOR, ID_DIRECCION, RTN, ID_TEL, CORREO, ID_VENDEDOR) VALUES (2, 'Proveedor B', 2, '0801-2222222', 2, 'info@proveedorb.com', 2)
SELECT * FROM dual;