"""create customers and vehicles tables

Revision ID: 1b224b5a2186
Revises: 1e94ffe69058
Create Date: 2026-10-07 00:32:46.058610

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1b224b5a2186"
down_revision: str | Sequence[str] | None = "1e94ffe69058"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workshop_id", sa.Uuid(), nullable=False),
        sa.Column("full_name", sa.String(length=120), nullable=False),
        sa.Column("phone", sa.String(length=8), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["workshop_id"], ["workshops.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_customers_workshop_id"), "customers", ["workshop_id"], unique=False)
    op.create_table(
        "vehicles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workshop_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("vehicle_type", sa.String(length=16), nullable=False),
        sa.Column("make", sa.String(length=60), nullable=False),
        sa.Column("model", sa.String(length=60), nullable=True),
        sa.Column("year", sa.SmallInteger(), nullable=True),
        sa.Column("color", sa.String(length=30), nullable=True),
        sa.Column("plate", sa.String(length=12), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "vehicle_type IN ('car', 'motorcycle', 'other')", name="ck_vehicles_vehicle_type"
        ),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"]),
        sa.ForeignKeyConstraint(["workshop_id"], ["workshops.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vehicles_customer_id"), "vehicles", ["customer_id"], unique=False)
    op.create_index(op.f("ix_vehicles_workshop_id"), "vehicles", ["workshop_id"], unique=False)
    op.create_index(
        "uq_vehicles_workshop_plate_active",
        "vehicles",
        ["workshop_id", "plate"],
        unique=True,
        postgresql_where=sa.text("archived_at IS NULL AND plate IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_vehicles_workshop_plate_active",
        table_name="vehicles",
        postgresql_where=sa.text("archived_at IS NULL AND plate IS NOT NULL"),
    )
    op.drop_index(op.f("ix_vehicles_workshop_id"), table_name="vehicles")
    op.drop_index(op.f("ix_vehicles_customer_id"), table_name="vehicles")
    op.drop_table("vehicles")
    op.drop_index(op.f("ix_customers_workshop_id"), table_name="customers")
    op.drop_table("customers")
    # ### end Alembic commands ###
