"""create inventory items and movements tables

Revision ID: 3571335f9414
Revises: d0876057935d
Create Date: 2026-10-06 15:40:55.120000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3571335f9414"
down_revision: str | Sequence[str] | None = "d0876057935d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Case- and accent-insensitive uniqueness/search needs `unaccent()`
#: (e.g. "bateria" must match "batería"). Enabled here since this is the
#: first migration that needs it.
_UNACCENT_EXTENSION = "unaccent"

#: Active item names are unique per workshop, case- and accent-insensitively.
#: Not expressible as a plain SQLAlchemy UniqueConstraint (it needs a partial,
#: functional index), so it is created and dropped with raw SQL.
_ACTIVE_NAME_INDEX = "ix_inventory_items_active_name"

#: `unaccent()` itself is STABLE, not IMMUTABLE (its result depends on the
#: configured text search dictionary), so Postgres refuses it directly in an
#: index expression ("functions in index expression must be marked
#: IMMUTABLE"). This wrapper pins the dictionary explicitly (the two-argument
#: form) and folds case, so it is safe to mark IMMUTABLE; the application
#: layer uses the exact same function for its search/uniqueness queries
#: (see taller.inventory.adapters.repositories), so the index is actually
#: usable.
#:
#: Deliberately `LANGUAGE plpgsql`, not the more obvious single-statement
#: `LANGUAGE sql`: a single-statement SQL function is eligible for inline
#: expansion, and Postgres inlines it while validating the CREATE UNIQUE
#: INDEX below -- in the same transaction as CREATE EXTENSION, that inlined
#: resolution of 'unaccent'::regdictionary fails with "text search
#: dictionary unaccent does not exist" even though the extension was just
#: created. plpgsql functions are never inlined, which avoids it.
_UNACCENT_LOWER_FUNCTION = "taller_unaccent_lower"


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(f"CREATE EXTENSION IF NOT EXISTS {_UNACCENT_EXTENSION}")
    op.execute(
        f"CREATE OR REPLACE FUNCTION {_UNACCENT_LOWER_FUNCTION}(text) RETURNS text AS $$ "
        "BEGIN "
        "RETURN lower(unaccent('unaccent'::regdictionary, $1)); "
        "END; "
        "$$ LANGUAGE plpgsql IMMUTABLE PARALLEL SAFE STRICT"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inventory_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workshop_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("category", sa.String(length=120), nullable=True),
        sa.Column("unit", sa.String(length=40), server_default="unidad", nullable=False),
        sa.Column("min_stock", sa.Integer(), server_default="0", nullable=False),
        sa.Column("sale_price_cents", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("stock", sa.Integer(), server_default="0", nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["workshop_id"], ["workshops.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inventory_items_workshop_id"), "inventory_items", ["workshop_id"], unique=False
    )
    op.create_table(
        "inventory_movements",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workshop_id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("delta", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"]),
        sa.ForeignKeyConstraint(["item_id"], ["inventory_items.id"]),
        sa.ForeignKeyConstraint(["workshop_id"], ["workshops.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inventory_movements_item_id"), "inventory_movements", ["item_id"], unique=False
    )
    op.create_index(
        op.f("ix_inventory_movements_workshop_id"),
        "inventory_movements",
        ["workshop_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    # Speeds up "an item's history, newest first" (GET /items/{id}/movements).
    op.create_index(
        "ix_inventory_movements_item_id_recorded_at",
        "inventory_movements",
        ["item_id", "recorded_at"],
    )

    # Partial, functional unique index: enforces the "active item names are
    # unique per workshop, case- and accent-insensitively" domain rule at
    # the database level, as the real guarantee behind the application's
    # pre-insert check (see taller.inventory.application.use_cases).
    op.execute(
        f"CREATE UNIQUE INDEX {_ACTIVE_NAME_INDEX} "
        f"ON inventory_items (workshop_id, {_UNACCENT_LOWER_FUNCTION}(name)) "
        "WHERE archived_at IS NULL"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute(f"DROP INDEX IF EXISTS {_ACTIVE_NAME_INDEX}")
    op.drop_index("ix_inventory_movements_item_id_recorded_at", table_name="inventory_movements")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_inventory_movements_workshop_id"), table_name="inventory_movements")
    op.drop_index(op.f("ix_inventory_movements_item_id"), table_name="inventory_movements")
    op.drop_table("inventory_movements")
    op.drop_index(op.f("ix_inventory_items_workshop_id"), table_name="inventory_items")
    op.drop_table("inventory_items")
    # ### end Alembic commands ###

    op.execute(f"DROP FUNCTION IF EXISTS {_UNACCENT_LOWER_FUNCTION}(text)")
    op.execute(f"DROP EXTENSION IF EXISTS {_UNACCENT_EXTENSION}")
